local Milestones = {}

Milestones.milestones_presets = function()
  return {
    ["Space Exploration"] = {
      required_mods = {"space-exploration"},
      milestones = {
        {type="group",      name="Science"},
        {type="item",       name="automation-science-pack",      quantity=1},
        {type="item",       name="logistic-science-pack",        quantity=1},
        {type="item",       name="military-science-pack",        quantity=1},
        {type="item",       name="chemical-science-pack",        quantity=1},
        {type="item",       name="se-rocket-science-pack",       quantity=1},
        {type="item",       name="space-science-pack",           quantity=1},
        {type="item",       name="production-science-pack",      quantity=1},
        {type="item",       name="utility-science-pack",         quantity=1},
        {type="item",       name="se-significant-data",          quantity=1},
        {type="item",       name="se-astronomic-science-pack-1", quantity=1},
        {type="item",       name="se-astronomic-science-pack-2", quantity=1},
        {type="item",       name="se-astronomic-science-pack-3", quantity=1},
        {type="item",       name="se-astronomic-science-pack-4", quantity=1},
        {type="item",       name="se-biological-science-pack-1", quantity=1},
        {type="item",       name="se-biological-science-pack-2", quantity=1},
        {type="item",       name="se-biological-science-pack-3", quantity=1},
        {type="item",       name="se-biological-science-pack-4", quantity=1},
        {type="item",       name="se-energy-science-pack-1",     quantity=1},
        {type="item",       name="se-energy-science-pack-2",     quantity=1},
        {type="item",       name="se-energy-science-pack-3",     quantity=1},
        {type="item",       name="se-energy-science-pack-4",     quantity=1},
        {type="item",       name="se-material-science-pack-1",   quantity=1},
        {type="item",       name="se-material-science-pack-2",   quantity=1},
        {type="item",       name="se-material-science-pack-3",   quantity=1},
        {type="item",       name="se-material-science-pack-4",   quantity=1},
        {type="item",       name="se-deep-space-science-pack-1", quantity=1},
        {type="item",       name="se-deep-space-science-pack-2", quantity=1},
        {type="item",       name="se-deep-space-science-pack-3", quantity=1},
        {type="item",       name="se-deep-space-science-pack-4", quantity=1},
        {type="item",       name="se-significant-data",          quantity=1000, next="x10"},

        {type="group",      name="Resources"},
        {type="fluid",      name="petroleum-gas",                quantity=1},
        {type="item",       name="se-core-fragment-omni",        quantity=1},
        {type="item",       name="se-vulcanite-block",           quantity=1},
        {type="item",       name="se-cryonite-rod",              quantity=1},
        {type="item",       name="se-vitamelange-spice",         quantity=1},
        {type="item",       name="se-beryllium-ingot",           quantity=1},
        {type="item",       name="se-holmium-ingot",             quantity=1},
        {type="item",       name="se-iridium-ingot",             quantity=1},
        {type="item",       name="se-naquium-ingot",             quantity=1},
        {type="item",       name="se-arcosphere",                quantity=1},

        {type="group",      name="Progress"},
        {type="item",       name="locomotive",                   quantity=1},
        {type="item",       name="construction-robot",           quantity=1},
        {type="item",       name="se-rocket-launch-pad-silo-dummy-result-item", quantity=1, next="x10"},
        {type="item",       name="requester-chest",              quantity=1},
        {type="technology", name="se-spaceship",                 quantity=1},
        {type="item",       name="se-space-elevator",            quantity=1},
        {type="item",       name="se-dimensional-anchor",        quantity=8, hidden=true},
        {type="technology", name="se-long-range-star-mapping",   quantity=1, hidden=true},
        {type="technology", name="se-spaceship-victory",         quantity=1},

        {type="group",      name="Kills"},
        {type="kill",       name="medium-biter",                 quantity=1},
        {type="kill",       name="big-biter",                    quantity=1},
        {type="kill",       name="behemoth-biter",               quantity=1},
        {type="kill",       name="behemoth-biter",               quantity=1000, next="x10"},
        {type="item",       name="se-plague-bomb",               quantity=1},
        {type="kill",       name="character",                    quantity=1, next="x5", hidden=true},
      }
    },
    ["Space Exploration + Krastorio 2"] = {
      required_mods = {"space-exploration", "Krastorio2"},
      milestones = {
        {type="group",      name="Science"},
        {type="item",       name="kr-basic-tech-card",           quantity=1},
        {type="item",       name="automation-science-pack",      quantity=1},
        {type="item",       name="logistic-science-pack",        quantity=1},
        {type="item",       name="military-science-pack",        quantity=1},
        {type="item",       name="chemical-science-pack",        quantity=1},
        {type="item",       name="se-rocket-science-pack",       quantity=1},
        {type="item",       name="space-science-pack",           quantity=1},
        {type="item",       name="kr-optimization-tech-card",    quantity=1},
        {type="item",       name="production-science-pack",      quantity=1},
        {type="item",       name="utility-science-pack",         quantity=1},
        {type="item",       name="se-significant-data",          quantity=1},
        {type="item",       name="se-astronomic-science-pack-1", quantity=1},
        {type="item",       name="se-astronomic-science-pack-2", quantity=1},
        {type="item",       name="se-astronomic-science-pack-3", quantity=1},
        {type="item",       name="se-astronomic-science-pack-4", quantity=1},
        {type="item",       name="se-biological-science-pack-1", quantity=1},
        {type="item",       name="se-biological-science-pack-2", quantity=1},
        {type="item",       name="se-biological-science-pack-3", quantity=1},
        {type="item",       name="se-biological-science-pack-4", quantity=1},
        {type="item",       name="se-energy-science-pack-1",     quantity=1},
        {type="item",       name="se-energy-science-pack-2",     quantity=1},
        {type="item",       name="se-energy-science-pack-3",     quantity=1},
        {type="item",       name="se-energy-science-pack-4",     quantity=1},
        {type="item",       name="se-material-science-pack-1",   quantity=1},
        {type="item",       name="se-material-science-pack-2",   quantity=1},
        {type="item",       name="se-material-science-pack-3",   quantity=1},
        {type="item",       name="se-material-science-pack-4",   quantity=1},
        {type="item",       name="kr-matter-tech-card",          quantity=1},
        {type="item",       name="se-kr-matter-science-pack-2",  quantity=1},
        {type="item",       name="kr-advanced-tech-card",        quantity=1},
        {type="item",       name="kr-singularity-tech-card",     quantity=1},
        {type="item",       name="se-deep-space-science-pack-1", quantity=1},
        {type="item",       name="se-deep-space-science-pack-2", quantity=1},
        {type="item",       name="se-deep-space-science-pack-3", quantity=1},
        {type="item",       name="se-deep-space-science-pack-4", quantity=1},
        {type="item",       name="se-significant-data",          quantity=1000, next="x10"},

        {type="group",      name="Resources"},
        {type="fluid",      name="petroleum-gas",                quantity=1},
        {type="item",       name="kr-silicon",                   quantity=1},
        {type="item",       name="se-core-fragment-omni",        quantity=1},
        {type="item",       name="se-vulcanite-block",           quantity=1},
        {type="item",       name="se-cryonite-rod",              quantity=1},
        {type="item",       name="se-vitamelange-spice",         quantity=1},
        {type="item",       name="se-beryllium-ingot",           quantity=1},
        {type="item",       name="se-holmium-ingot",             quantity=1},
        {type="item",       name="se-iridium-ingot",             quantity=1},
        {type="fluid",      name="kr-mineral-water",             quantity=1},
        {type="item",       name="kr-rare-metals",               quantity=1},
        {type="item",       name="kr-imersite-powder",           quantity=1},
        {type="item",       name="se-naquium-ingot",             quantity=1},
        {type="item",       name="se-arcosphere",                quantity=1},

        {type="group",      name="Progress"},
        {type="item",       name="locomotive",                   quantity=1},
        {type="item",       name="construction-robot",           quantity=1},
        {type="item",       name="se-rocket-launch-pad-silo-dummy-result-item", quantity=1, next="x10"},
        {type="item",       name="requester-chest",              quantity=1},
        {type="technology", name="se-spaceship",                 quantity=1},
        {type="item",       name="se-space-elevator",            quantity=1},
        {type="technology", name="kr-advanced-pickaxe",          quantity=1},
        {type="item",       name="kr-ai-core",                   quantity=1},
        {type="fluid",      name="kr-matter",                    quantity=1},
        {type="item",       name="se-dimensional-anchor",        quantity=8, hidden=true},
        {type="technology", name="se-long-range-star-mapping",   quantity=1, hidden=true},
        {type="item",       name="kr-intergalactic-transceiver", quantity=1},
        {type="technology", name="se-spaceship-victory",         quantity=1},

        {type="group",      name="Kills"},
        {type="kill",       name="medium-biter",                 quantity=1},
        {type="kill",       name="big-biter",                    quantity=1},
        {type="kill",       name="behemoth-biter",               quantity=1},
        {type="kill",       name="behemoth-biter",               quantity=1000, next="x10"},
        {type="item",       name="se-plague-bomb",               quantity=1},
        {type="kill",       name="character",                    quantity=1, next="x5", hidden=true},
      }
    },
  }
end

return Milestones
