data:extend({
  {
    type = "recipe",
    name = "kr-advanced-underground-belt",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "express-underground-belt", amount = 2 },
      { type = "item", name = "kr-advanced-transport-belt", amount = 30 },
    },
    results = { { type = "item", name = "kr-advanced-underground-belt", amount = 2 } },
  },
  {
    type = "item",
    name = "kr-advanced-underground-belt",
    icon = "__PriyUtils__/graphics/icons/entities/advanced-underground-belt.png",
    subgroup = "belt",
    order = "b[underground-belt]-d[advanced-underground-belt]",
    place_result = "kr-advanced-underground-belt",
    stack_size = 50,
  },
  {
    type = "underground-belt",
    name = "kr-advanced-underground-belt",
    icon = "__PriyUtils__/graphics/icons/entities/advanced-underground-belt.png",
    flags = { "placeable-neutral", "player-creation" },
    fast_replaceable_group = "transport-belt",
    next_upgrade = "kr-superior-underground-belt",
    minable = { mining_time = 0.2, result = "kr-advanced-underground-belt" },
    collision_box = { { -0.4, -0.4 }, { 0.4, 0.4 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    max_distance = 30,
    speed = 0.125,
    max_health = 200,
    corpse = "kr-advanced-underground-belt-remnants",
    resistances = {
      {
        type = "fire",
        percent = 50,
      },
      {
        type = "impact",
        percent = 30,
      },
    },
    belt_animation_set = {
      animation_set = {
        filename = "__PriyUtils__/graphics/buildings/advanced-transport-belt/advanced-transport-belt.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
        frame_count = 32,
        direction_count = 20,
      },
      east_index = 1,
      west_index = 2,
      north_index = 3,
      south_index = 4,
      east_to_north_index = 5,
      north_to_east_index = 6,
      west_to_north_index = 7,
      north_to_west_index = 8,
      south_to_east_index = 9,
      east_to_south_index = 10,
      south_to_west_index = 11,
      west_to_south_index = 12,
      starting_south_index = 13,
      ending_south_index = 14,
      starting_west_index = 15,
      ending_west_index = 16,
      starting_north_index = 17,
      ending_north_index = 18,
      starting_east_index = 19,
      ending_east_index = 20,
    },
    structure = {
      direction_in = {
        sheet = {
          filename = "__PriyUtils__/graphics/buildings/advanced-underground-belt/advanced-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          y = 192,
          scale = 0.5,
        },
      },
      direction_out = {
        sheet = {
          filename = "__PriyUtils__/graphics/buildings/advanced-underground-belt/advanced-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          scale = 0.5,
        },
      },
      direction_in_side_loading = {
        sheet = {
          filename = "__PriyUtils__/graphics/buildings/advanced-underground-belt/advanced-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          y = 192 * 3,
          scale = 0.5,
        },
      },
      direction_out_side_loading = {
        sheet = {
          filename = "__PriyUtils__/graphics/buildings/advanced-underground-belt/advanced-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          y = 192 * 2,
          scale = 0.5,
        },
      },
      back_patch = {
        sheet = {
          filename = "__PriyUtils__/graphics/buildings/advanced-underground-belt/advanced-underground-belt-structure-back-patch.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          scale = 0.5,
        },
      },
      front_patch = {
        sheet = {
          filename = "__PriyUtils__/graphics/buildings/advanced-underground-belt/advanced-underground-belt-structure-front-patch.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          scale = 0.5,
        },
      },
    },
    underground_sprite = {
      filename = "__core__/graphics/arrows/underground-lines.png",
      priority = "high",
      width = 64,
      height = 64,
      x = 64,
      scale = 0.5,
    },
    underground_remove_belts_sprite = {
      filename = "__core__/graphics/arrows/underground-lines-remove.png",
      priority = "high",
      width = 64,
      height = 64,
      x = 64,
      scale = 0.5,
    },
    animation_speed_coefficient = 28,
  },
})
