data:extend({
  {
    type = "recipe",
    name = "kr-advanced-splitter",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "express-splitter", amount = 1 },
      { type = "item", name = "steel-plate", amount = 4 },
      { type = "item", name = "advanced-circuit", amount = 1 },
    },
    results = { { type = "item", name = "kr-advanced-splitter", amount = 1 } },
  },
  {
    type = "item",
    name = "kr-advanced-splitter",
    localised_description = { "entity-description.splitter" },
    icon = "__PriyUtils__/graphics/icons/entities/advanced-splitter.png",
    subgroup = "belt",
    order = "c[splitter]-d[advanced-splitter]",
    place_result = "kr-advanced-splitter",
    stack_size = 50,
  },
  {
    type = "splitter",
    name = "kr-advanced-splitter",
    localised_description = { "entity-description.splitter" },
    icon = "__PriyUtils__/graphics/icons/entities/advanced-splitter.png",
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 0.2, result = "kr-advanced-splitter" },
    collision_box = { { -0.9, -0.4 }, { 0.9, 0.4 } },
    selection_box = { { -0.9, -0.5 }, { 0.9, 0.5 } },
    fast_replaceable_group = "transport-belt",
    next_upgrade = "kr-superior-splitter",
    speed = 0.125,
    max_health = 250,
    corpse = "kr-advanced-splitter-remnants",
    icon_draw_specification = { scale = 0.5 },
    resistances = {
      {
        type = "fire",
        percent = 50,
      },
    },
    belt_animation_set = {
      animation_set = {
        filename = "__PriyUtils__/graphics/buildings/advanced-transport-belt/advanced-transport-belt.png",
        priority = "extra-high",
        width = 128,
        height = 128,
        scale = 0.5,
        frame_count = 32,
        direction_count = 20,
      },
      east_index = 1,
      west_index = 2,
      north_index = 3,
      south_index = 4,
      east_to_north_index = 5,
      north_to_east_index = 6,
      west_to_north_index = 7,
      north_to_west_index = 8,
      south_to_east_index = 9,
      east_to_south_index = 10,
      south_to_west_index = 11,
      west_to_south_index = 12,
      starting_south_index = 13,
      ending_south_index = 14,
      starting_west_index = 15,
      ending_west_index = 16,
      starting_north_index = 17,
      ending_north_index = 18,
      starting_east_index = 19,
      ending_east_index = 20,
    },
    structure = {
      north = {
        filename = "__PriyUtils__/graphics/buildings/advanced-splitter/advanced-splitter-north.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 160,
        height = 70,
        shift = util.by_pixel(7, 0),
        scale = 0.5,
      },
      east = {
        filename = "__PriyUtils__/graphics/buildings/advanced-splitter/advanced-splitter-east.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 84,
        shift = util.by_pixel(4, 13),
        scale = 0.5,
      },
      south = {
        filename = "__PriyUtils__/graphics/buildings/advanced-splitter/advanced-splitter-south.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 164,
        height = 64,
        shift = util.by_pixel(4, 0),
        scale = 0.5,
      },
      west = {
        filename = "__PriyUtils__/graphics/buildings/advanced-splitter/advanced-splitter-west.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 86,
        shift = util.by_pixel(6, 12),
        scale = 0.5,
      },
    },
    structure_patch = {
      north = util.empty_sprite(),
      east = {
        filename = "__PriyUtils__/graphics/buildings/advanced-splitter/advanced-splitter-east-top_patch.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 104,
        shift = util.by_pixel(4, -20),
        scale = 0.5,
      },
      south = util.empty_sprite(),
      west = {
        filename = "__PriyUtils__/graphics/buildings/advanced-splitter/advanced-splitter-west-top_patch.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 96,
        shift = util.by_pixel(6, -18),
        scale = 0.5,
      },
    },
    circuit_wire_max_distance = splitter_circuit_wire_max_distance,
    circuit_connector = circuit_connector_definitions["splitter"],
    default_input_left_condition = { first = { type = "virtual", name = "signal-I" }, comparator = "<", second = 0 },
    default_input_right_condition = { first = { type = "virtual", name = "signal-I" }, comparator = ">", second = 0 },
    default_output_left_condition = { first = { type = "virtual", name = "signal-O" }, comparator = "<", second = 0 },
    default_output_right_condition = { first = { type = "virtual", name = "signal-O" }, comparator = ">", second = 0 },
    animation_speed_coefficient = 28,
    structure_animation_speed_coefficient = 1.2,
    structure_animation_movement_cooldown = 10,
  },
})
