data:extend({
  {
    type = "corpse",
    name = "kr-advanced-transport-belt-remnants",
    localised_name = { "remnant-name", { "entity-name.kr-advanced-transport-belt" } },
    icon = "__PriyUtils__/graphics/icons/entities/advanced-transport-belt.png",
    flags = { "placeable-neutral", "not-on-map" },
    hidden_in_factoriopedia = true,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    tile_width = 1,
    tile_height = 1,
    selectable_in_game = false,
    time_before_removed = 15 * minute,
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = make_rotated_animation_variations_from_sheet(8, {
      filename = "__PriyUtils__/graphics/remnants/advanced-transport-belt-remnants.png",
      line_length = 1,
      width = 106,
      height = 102,
      frame_count = 1,
      variation_count = 1,
      direction_count = 1,
      shift = util.by_pixel(1, -0.5),
      scale = 0.5,
    }),
  },
  {
    type = "corpse",
    name = "kr-superior-transport-belt-remnants",
    localised_name = { "remnant-name", { "entity-name.kr-superior-transport-belt" } },
    icon = "__PriyUtils__/graphics/icons/entities/superior-transport-belt.png",
    flags = { "placeable-neutral", "not-on-map" },
    hidden_in_factoriopedia = true,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    tile_width = 1,
    tile_height = 1,
    selectable_in_game = false,
    time_before_removed = 15 * minute,
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = make_rotated_animation_variations_from_sheet(8, {
      filename = "__PriyUtils__/graphics/remnants/superior-transport-belt-remnants.png",
      line_length = 1,
      width = 106,
      height = 102,
      frame_count = 1,
      variation_count = 1,
      direction_count = 1,
      shift = util.by_pixel(1, -0.5),
      scale = 0.5,
    }),
  },
  {
    type = "corpse",
    name = "kr-advanced-underground-belt-remnants",
    localised_name = { "remnant-name", { "entity-name.kr-advanced-underground-belt" } },
    icon = "__PriyUtils__/graphics/icons/entities/advanced-underground-belt.png",
    flags = { "placeable-neutral", "not-on-map", "building-direction-8-way" },
    hidden_in_factoriopedia = true,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    tile_width = 1,
    tile_height = 1,
    selectable_in_game = false,
    time_before_removed = 15 * minute,
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = {
      filename = "__PriyUtils__/graphics/remnants/advanced-underground-belt-remnants.png",
      line_length = 1,
      width = 116,
      height = 100,
      frame_count = 1,
      variation_count = 1,
      direction_count = 8,
      shift = util.by_pixel(3.5, 3.5),
      scale = 0.5,
    },
  },
  {
    type = "corpse",
    name = "kr-superior-underground-belt-remnants",
    localised_name = { "remnant-name", { "entity-name.kr-superior-underground-belt" } },
    icon = "__PriyUtils__/graphics/icons/entities/superior-underground-belt.png",
    flags = { "placeable-neutral", "not-on-map", "building-direction-8-way" },
    hidden_in_factoriopedia = true,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    tile_width = 1,
    tile_height = 1,
    selectable_in_game = false,
    time_before_removed = 15 * minute,
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = {
      filename = "__PriyUtils__/graphics/remnants/superior-underground-belt-remnants.png",
      line_length = 1,
      width = 116,
      height = 100,
      frame_count = 1,
      variation_count = 1,
      direction_count = 8,
      shift = util.by_pixel(3.5, 3.5),
      scale = 0.5,
    },
  },
  {
    type = "corpse",
    name = "kr-advanced-splitter-remnants",
    localised_name = { "remnant-name", { "entity-name.kr-advanced-splitter" } },
    icon = "__PriyUtils__/graphics/icons/entities/advanced-splitter.png",
    flags = { "placeable-neutral", "not-on-map" },
    hidden_in_factoriopedia = true,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    selection_box = { { -0.9, -0.5 }, { 0.9, 0.5 } },
    tile_width = 2,
    tile_height = 1,
    selectable_in_game = false,
    time_before_removed = 15 * minute,
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = {
      filename = "__PriyUtils__/graphics/remnants/advanced-splitter-remnants.png",
      line_length = 1,
      width = 172,
      height = 156,
      frame_count = 1,
      variation_count = 1,
      direction_count = 4,
      shift = util.by_pixel(1, 3),
      scale = 0.5,
    },
  },
  {
    type = "corpse",
    name = "kr-superior-splitter-remnants",
    localised_name = { "remnant-name", { "entity-name.kr-superior-splitter" } },
    icon = "__PriyUtils__/graphics/icons/entities/superior-splitter.png",
    flags = { "placeable-neutral", "not-on-map" },
    hidden_in_factoriopedia = true,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    selection_box = { { -0.9, -0.5 }, { 0.9, 0.5 } },
    tile_width = 2,
    tile_height = 1,
    selectable_in_game = false,
    time_before_removed = 15 * minute,
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = {
      filename = "__PriyUtils__/graphics/remnants/superior-splitter-remnants.png",
      line_length = 1,
      width = 172,
      height = 156,
      frame_count = 1,
      variation_count = 1,
      direction_count = 4,
      shift = util.by_pixel(1, 3),
      scale = 0.5,
    },
  },
})
